TITLE = 'Neural Network Visualiser'
TILESIZE = 16
MAP_WIDTH = 32
MAP_HEIGHT = 32
GRID_WIDTH = MAP_WIDTH * TILESIZE
GRID_HEIGHT = MAP_HEIGHT * TILESIZE
TOTAL_WIDTH = 2 * GRID_WIDTH

FPS = 64

POPULATION_SIZE = 100
ELITISM = 0.5
ELITE_QTY = int(POPULATION_SIZE * ELITISM)
MUTATION_RATE = 0.2

INPUTS = 8
HNODES = 5
OUTPUTS = 3

SNAKE_START_LENGTH = 3
SNAKE_START_X = int(MAP_WIDTH / 2)
SNAKE_START_Y = int(MAP_HEIGHT / 2)
SNAKE_MAX_FULLNESS = 100

LAYER_IN_X = GRID_WIDTH + int(GRID_WIDTH/4)
LAYER_H_X = GRID_WIDTH + 2*int(GRID_WIDTH/4)
LAYER_OUT_X = GRID_WIDTH + 3*int(GRID_WIDTH/4)
INPUT_YSTEP = int(GRID_HEIGHT / (INPUTS + 1))
HIDDEN_YSTEP = int(GRID_HEIGHT / (HNODES + 1))
OUTPUT_YSTEP = int(GRID_HEIGHT / (OUTPUTS + 1))

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREY = (50, 50, 50)
RED = (200, 0, 0)
GREEN = (0, 200, 0)